name: "Test devenv changes"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - devenv.nix
      - devenv.yaml
      - .devcontainer.json

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Cache
      uses: actions/cache@v3.3.2
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: /nix
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-primes

    - uses: cachix/install-nix-action@v23
    - uses: cachix/cachix-action@v12
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install tarball+https://install.devenv.sh/latest

    - name: Build the devenv shell and run any pre-commit hooks
      run: devenv ci

    - name: Gulp Lint
      run: devenv shell gulp lint
